worker_processes 1;
worker_rlimit_nofile 8192;

events {
    worker_connections 4096;
    use epoll;
    multi_accept on;
}

http {
    access_log off;
    error_log /dev/null crit;

    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 30;
    keepalive_requests 10000;

    upstream apis {
        # round-robin padrão; sem least_conn para não parecer lógica
        server api-1:3000 max_fails=0;
        server api-2:3000 max_fails=0;
        keepalive 256;
    }

    server {
        listen 9999 default_server backlog=4096;

        location / {
            proxy_pass http://apis;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_buffering off;
        }
    }
}
